#!/bin/bash
#no space in bash to identify variable, no space between operators (eg. = in this file)
sum=0
for i in $@ #$1 $2 $3 $4 $5 use as many as need to get the same amount of type-in, start from 1 not 0 
# $@ saves multiple inputs
do
    sum=$((i + $sum)) #dollar sign to grabing a variable's value
done
echo $sum
